### ISSUE TITLE
Dupe license, missing license

### ISSUE THREAD

**Issue by taikedz** [azekillDIABLO/mila#3]
Needs license advisory from the original creators of the artwork textures

Need to delete duplicate license file regarding the code

**Comment by RodrigueLemaire** [comment]
ok sir!

**Comment by RodrigueLemaire** [comment]
that isn't a dupe, it's for the .. ok yes it was done intentionally but github needs this "license" file and if nooby user start searching things in MILA they won't know how to open a file without extension.

**Comment by RodrigueLemaire** [comment]
i'll take care of getting licenses sorry i can't upload them right now.

**Comment by RodrigueLemaire** [comment]
as dOOmed told me, i'm seaching license for models and textures! :100:

**Comment by RodrigueLemaire** [comment]
I'll close this as the 1.1 will be the last version with those mobs. They will then be deleted and i'll try to use my own stuff.
